version: '3.7'

services:
  web:
    build: .
    command: sh -c "gunicorn django_project.wsgi:application --bind 0.0.0.0:8000 && 
                    python manage.py migrate --noinput &&
                    python manage.py collectstatic --no-input --clear"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: 